# Generated by Django 4.0.6 on 2024-09-09 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordemServico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='repositorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ordemServico.repositorio'),
        ),
    ]
