# Generated by Django 4.0.6 on 2024-09-09 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordemServico', '0002_alter_servico_repositorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='ordem_servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ordemServico.ordemservico'),
        ),
    ]
