# Generated by Django 4.0.6 on 2024-09-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemServico', '0003_alter_tarefa_ordem_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(blank=True, choices=[('nao_iniciada', 'NÃO INICIADA'), ('em_andamento', 'EM ENDAMENTO'), ('concluida', 'CONCLUÍDA')], default='nao_iniciada', max_length=15, null=True),
        ),
    ]
