# Generated by Django 4.0.6 on 2024-09-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemServico', '0004_alter_tarefa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='faturamento',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=5, null=True),
        ),
    ]
