# Generated by Django 4.0.6 on 2024-09-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemServico', '0005_alter_ordemservico_faturamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cliente_ativo',
            field=models.CharField(blank=True, choices=[('sim', 'SIM'), ('nao', 'NÃO')], default='sim', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome_fantasia',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero_inscricao',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(blank=True, choices=[('gestao', 'Gestão'), ('avulso', 'Avulso'), ('fornecedor', 'Fornecedor')], default='gestao', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_inscricao',
            field=models.CharField(blank=True, choices=[('cnpj', 'CNPJ'), ('cpf', 'CPF'), ('cei', 'CEI'), ('cno', 'CNO'), ('caepf', 'CAEPF')], default='cnpj', max_length=10, null=True),
        ),
    ]
