# Generated by Django 4.0.6 on 2024-09-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemServico', '0006_cliente_cliente_ativo_cliente_nome_fantasia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='minios',
            name='quantidade',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
