# Generated by Django 4.0.6 on 2024-09-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemServico', '0008_minios_data_recebimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minios',
            name='data_recebimento',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
