# Generated by Django 4.0.6 on 2024-09-15 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemServico', '0010_alter_cliente_nome_fantasia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='valor',
            field=models.FloatField(blank=True, default=' ', null=True),
        ),
    ]
