# Generated by Django 4.0.6 on 2024-09-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemServico', '0011_alter_ordemservico_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='valor',
            field=models.FloatField(blank=True, default='0.0', null=True),
        ),
    ]
