# Generated by Django 4.0.6 on 2024-09-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemServico', '0012_alter_ordemservico_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='data_conclusao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
