# Generated by Django 4.0.6 on 2024-09-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemServico', '0013_servico_data_conclusao'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servico',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nome_fantasia',
        ),
        migrations.AlterField(
            model_name='servico',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
