# Generated by Django 4.0.6 on 2024-09-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemServico', '0014_alter_servico_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nome_fantasia',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
