# Generated by Django 5.2 on 2026-01-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemServico', '0017_alter_servico_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Contato',
        ),
    ]
