# Generated by Django 5.2 on 2026-01-09 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordemServico', '0018_profile_active_delete_contato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='token',
        ),
    ]
