# Generated by Django 5.2 on 2026-01-09 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordemServico', '0019_remove_profile_cpf_remove_profile_profile_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='renovacao_automatica',
        ),
    ]
